Updating to reflect addition of Metrics Logstream
statsig-io/docs pull request #334
Opened 2022-07-13 23:42 UTC by mseger-statsig

Adding the metrics logstream as a way to debug precomputed metrics

2022-07-13 23:44 UTC, jasonwzm commented
<!-- NETLIFY DEPLOY COMMENT GENERATED BY ACTIONS_NETLIFY - APP ID SHA256: 0038af8fad421c48cf2dd5ee95e08d2d419533ec7208a507c5ccd1696cdf8b44 -->
🚀 Deployed on https://62cf58abbad44b5ada62ffae--cozy-fox-0defec.netlify.app

2022-07-14 01:09 UTC, craig-statsig commented on docs/metrics/ingest.md
> +
Nit: this is in the first step of ingestion. If they don’t show up, there is a connection or schema issue

2022-07-14 01:10 UTC, craig-statsig commented on docs/metrics/ingest.md
> +To set this **isTest** flag in the ingestion API-
We don’t have the schema for this yet so may want to omit it for now

2022-07-14 01:10 UTC, craig-statsig requested changes
See comments

2022-07-14 18:05 UTC, craig-statsig approved these changes

2022-07-14 18:08 UTC, merged